name: release

on:
  workflow_dispatch:
  create:
    tags:
      - '*'

jobs:
  release:
    if: (github.event_name == 'create' && github.event.ref_type == 'tag')
    runs-on: ubuntu-latest
    steps:
      - name: 'Set up JDK'
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: 'Prepare git'
        run: git config --global core.autocrlf false

      - name: 'Prepare branch name'
        if: (github.event_name == 'create' && github.event.ref_type == 'tag')
        run: >
          echo "refName=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: 'Checkout relevant branch'
        uses: actions/checkout@v4
        with:
          ref: ${{ env.refName }}
          fetch-depth: 0

      - name: Determine revision
        id: revision_step
        run: |
          REVISION=$(./bin/extract-version.sh latest)
          echo "REVISION=$REVISION" >> $GITHUB_ENV

      - name: 'Create release'
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.JRELEASER_TOKEN }}
          JRELEASER_SLACK_WEBHOOK: ${{ secrets.JRELEASER_SLACK_WEBHOOK }}
        run: ./mvnw --no-transfer-progress -Djreleaser -Drevision=$REVISION -Dsha1= -Dchangelist= jreleaser:announce -pl org.neo4j:neo4j-cypher-dsl-parent
